# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish -o ${{env.DOTNET_ROOT}}/publish
    - name: Upload to Artifact Store
      uses: actions/upload-artifact@v3
      with:
        name: my-artifacts
        path: ${{env.DOTNET_ROOT}}/publish
    
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifacts to VM
        uses: actions/download-artifact@v3
        with:
          name: my-artifacts

